# Generated by Django 3.2.11 on 2022-01-31 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='data2',
            new_name='rollno',
        ),
    ]
