# Generated by Django 3.2.11 on 2022-02-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
