# Generated by Django 3.2.11 on 2022-02-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20220204_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='content',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
