# Generated by Django 3.2.11 on 2022-02-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_top_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='certificate_name1',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='top',
            name='certificate_name2',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='top',
            name='skills1',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='top',
            name='skills2',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
