# Generated by Django 3.2.11 on 2022-02-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20220205_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top',
            name='certificate_name1',
        ),
        migrations.RemoveField(
            model_name='top',
            name='certificate_name2',
        ),
        migrations.RemoveField(
            model_name='top',
            name='skills1',
        ),
        migrations.RemoveField(
            model_name='top',
            name='skills2',
        ),
    ]
