# Generated by Django 3.2.11 on 2022-02-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20220205_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='certificate_name1',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='top',
            name='certificate_name2',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='top',
            name='company_name1',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='top',
            name='company_name2',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='top',
            name='description1',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='top',
            name='description2',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='top',
            name='designation1',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='top',
            name='designation2',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='top',
            name='skills1',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='top',
            name='skills2',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='top',
            name='tenure1',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='top',
            name='tenure2',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
