# Generated by Django 3.2.11 on 2022-02-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20220206_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='company_name1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='top',
            name='company_name2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='top',
            name='description1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='top',
            name='description2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='top',
            name='designation1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='top',
            name='designation2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='top',
            name='tenure1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='top',
            name='tenure2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
