# Generated by Django 3.2.11 on 2022-02-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20220206_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='portfolio_link',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
